### ISSUE TITLE
Getting '401 Unauthorized' in ActiveClusterMonitor

### ISSUE THREAD

**Issue by pramesh94** [lyft/presto-gateway#168]
After registering a trino backend, I'm able to make queries via presto-gateway but I'm getting these messages in the logs:
`
WARN  [2022-04-25 06:00:24,403] com.lyft.data.gateway.ha.clustermonitor.ActiveClusterMonitor: Received non 200 response, response code: 401
`

I'm running trino version 371 with no UI authentication. The trino admin UI asks for a username (any username works) and generates a JWT auth token. This token is missing when we are making the API call to cluster from presto-gateway to get the cluster health information and hence we're getting 401.

Am I missing something here?

**Comment by pramesh94** [comment]
I was able to make it work after adding the below lines in config.properties of the coordinator

```
    web-ui.authentication.type=fixed
    web-ui.user=user
```

**Comment by jotarada** [comment]
I think this should be reopen. It works for non authenticated clusters, but i don't see how to make it work for authenticated clusters. I'm using password authenticated cluster and i'm having the same problem.
