### ISSUE TITLE
presto_cluster_state.json file not found

### ISSUE THREAD

**Issue by skyahead** [lyft/presto-gateway#53]
I am trying this repo on my laptop and run it for the first time, got this error:

ERROR [2019-07-10 23:06:30,233] com.lyft.data.gateway.router.impl.GatewayBackendManagerImpl: Could not read previous backend cluster state
! java.io.FileNotFoundException: /var/log/prestoproxy/cache/presto_cluster_state.json (No such file or directory)
!

**Comment by puneetjaiswal** [comment]
@skyahead 
This happened because you do not have `cacheDir` present. Can you please run the following commands
```
sudo mkdir -p /var/log/prestoproxy/cache
chown -R `id -u`:`id -g` /var/log/prestoproxy/
```
Please feel free to add a PR to update the setup instructions.

**Comment by skyahead** [comment]
I just did exactly what you instructed and got the same error. Maybe a better way is to initialize an empty json if this line fails?? https://github.com/lyft/presto-gateway/blob/master/gateway/src/main/java/com/lyft/data/gateway/router/impl/GatewayBackendManagerImpl.java#L108

**Comment by skyahead** [comment]
If I create that file manually and add `{}` in it, the code works.

**Comment by puneetjaiswal** [comment]
@skyahead - Its a harmless warning, did the application start after creating the `cacheDir` ? 
May be we should change the [log level](Could not read previous backend cluster state) to `warn` instead of `error`.

**Comment by puneetjaiswal** [comment]
> I just did exactly what you instructed and got the same error. Maybe a better way is to initialize an empty json if this line fails?? https://github.com/lyft/presto-gateway/blob/master/gateway/src/main/java/com/lyft/data/gateway/router/impl/GatewayBackendManagerImpl.java#L108

The cluster state file is [created](https://github.com/lyft/presto-gateway/blob/master/gateway/src/main/java/com/lyft/data/gateway/router/impl/GatewayBackendManagerImpl.java#L99) when active/de-active state is changed through API call. 
IMO, its a harmless warning.

**Comment by puneetjaiswal** [comment]
> If I create that file manually and add `{}` in it, the code works.

I would not recommend doing this, as this will override the cluster state loading from config file.

**Comment by skyahead** [comment]
Do you have somewhere to discuss things like this? 

Also, is it possible to use Presto cli to send queries to this gateway? I am trying and the cli times out while waiting for query status, with errors `Error running command: Error fetching next`

**Comment by puneetjaiswal** [comment]
Rephrased the logging message here - https://github.com/lyft/presto-gateway/pull/54/files#diff-6df3235fa747ebd415e084b03a5324bcR131
