### ISSUE TITLE
QueryIdCachingProxyHandler.java extractQueryIdIfPresent  logic error

### ISSUE THREAD

**Issue by rongfengliang** [lyft/presto-gateway#59]
extractQueryIdIfPresent methed in QueryIdCachingProxyHandler.java  get queryid may get error id  when  statement in  different statu, this will cause query routing error
like  this 
```code
/v1/statement/queued/20190823_150041_00020_bm7k5/xfe619af6efe0400296a6f29f80ce67ab/1
```

should do more check for path `/v1/statement/.....` if contains different statu

**Comment by puneetjaiswal** [comment]
Thanks @rongfengliang for reporting, would you have some cycles to send a PR for this fix?

**Comment by rongfengliang** [comment]
@puneetjaiswal  ok, i hava  fix it  [pr](https://github.com/lyft/presto-gateway/pull/60)

**Comment by puneetjaiswal** [comment]
Thanks @rongfengliang for adding the fix. Can you please sign the [CLA](https://oss.lyft.com/cla), then we can merge this.
