### ISSUE TITLE
DBeaver support or guide to connect using datagrip

### ISSUE THREAD

**Issue by PabloInnocenti** [lyft/presto-gateway#80]
Hi All, Thanks for this wonderfull project.
We would like to know if gateway supports DBeaver client ( via presto-jdbc driver).
Also if there is a guide how to connect to gateway using clients ( example DataGrip or SuperSet) or slack/google channel to chat.
Thanks!

**Comment by amitsingh-10** [comment]
Gateway is just a proxy for your Presto clusters. It should work with configuration as if the presto cluster was directly exposed. If you have used DataGrip or SuperSet to connect and execute queries on your Presto clusters directly, it should work seamlessly just with those configs/credentials.
