### ISSUE TITLE
Presto cluster stats broken when redirecting from the query UI

### ISSUE THREAD

**Issue by chets25** [lyft/presto-gateway#88]
When a user navigates in this flow:
 1. Go to the presto-gateway UI - `http://presto-gateway`
 2. Click on a query, which redirects to the presto query UI - `http://presto-gateway/ui/query.html`
 3. Click on the presto logo on the top left, which redirects to the presto cluster UI - `http://presto-gateway/ui`,

the cluster view is broken with the `v1/cluster` API returning `404` . (Image attached below) 

This is because the `v1/cluster` endpoint is currently not whitelisted. 
![image](https://user-images.githubusercontent.com/37013543/73209771-f264ce00-4116-11ea-9f75-ae6bd93723c2.png)

**Comment by AvianshKumar** [comment]
Hi @chets25 ,

i am able to make presto-gateway up and running but if I query from presto-cli then i am not able to get any query id in gateway history. and how we are providing support to presto for this presto-gateway and how you are redirecting to two different proxy?
please help....
